export {default as NavBar} from './NavBar'
export {default as Footer} from './Footer'
export {default as Layout} from './Layout'
export {default as Hero} from './Hero'
export {default as PopularProducts} from './PopularProducts'
export {default as Anounce} from './Anounce'
export {default as Features} from './Features'
export {default as CustomerFeedbacks} from './CustomerFeedbacks'
export {default as Sponsors} from './Sponsors'
export {default as NewsLetter} from './NewsLetter'
export {default as CustomButton} from './CustomButton'
export {default as SubcategoriesLayout} from './SubcategoriesLayout'
export{default as RecomendedProducts} from './RecomendedProducts'
export{default as ProductsFiltersLayout} from './ProductsFiltersLayout'


