export {default as Home} from './Home'
export {default as Products} from './Products'
export {default as ProductDetails} from './ProductDetails'
export {default as CartsPage} from './CartsPage'
export {default as Checkout} from './Checkout'