# Generated by Django 4.1.7 on 2023-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paymentmethod_payment_method_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_roles',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
