# Generated by Django 4.1.7 on 2023-04-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_user_roles_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.taxes'),
            preserve_default=False,
        ),
    ]
