# Generated by Django 4.1.7 on 2023-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taxes_order_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
