# Generated by Django 4.1.7 on 2023-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_taxes_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='description',
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
