# Generated by Django 4.1.7 on 2023-04-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_tax_rate_taxes_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_rate',
            new_name='tax',
        ),
    ]
