# Generated by Django 4.1.7 on 2023-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tax_rate_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
