# Generated by Django 4.1.7 on 2023-04-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_product_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
