# Generated by Django 4.1.7 on 2023-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hero', models.CharField(max_length=200)),
                ('title_anounce', models.CharField(max_length=200)),
                ('slug_hero', models.SlugField(blank=True, null=True, unique=True)),
                ('slug_anounce', models.SlugField(blank=True, null=True, unique=True)),
                ('image_hero', models.ImageField(upload_to='ads/')),
                ('image_anounce', models.ImageField(upload_to='ads/')),
                ('url_hero', models.URLField()),
                ('url_anounce', models.URLField()),
                ('start_date_hero', models.DateField()),
                ('start_date_anounce', models.DateField()),
                ('end_date_hero', models.DateField()),
                ('end_date_anounce', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
