# Generated by Django 4.1.7 on 2023-04-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ad_alter_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='slug_anounce',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='slug_hero',
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date_anounce',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date_hero',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_date_anounce',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_date_hero',
            field=models.DateTimeField(),
        ),
    ]
