# Generated by Django 4.1.7 on 2023-04-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_anouncead_heroad_delete_ad_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncead',
            name='description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
