# Generated by Django 4.1.7 on 2023-04-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_anouncead_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
