# Generated by Django 4.1.7 on 2023-04-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_customuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
